[package]
name = "logss"
version = "1.0.0-beta"
authors = ["Victor Rosales <todoesverso@gmail.com>"]
edition = "2021"
publish = false
repository = "https://github.com/todoesverso/logss"
keywords = ["terminal", "logs", "cli", "split"]
categories = ["visualization", "command-line-utilities", "parsing"]
license = "MIT"

[dependencies]
crossterm = "0.26.1"
is-terminal = "0.4.2"
unicode-width = "0.1.10"
pico-args = "0.5.0"
ratatui = "0.20.1"
regex = "1.8.4"
serde_yaml = "0.9.19"
serde = {version = "1.0.163", features = ["derive"]}

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
strip = true

[dev-dependencies]
assert_cmd = "2.0.10"
predicates = "3.0.2"
